api:
  dashboard: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    directory: /etc/traefik/conf

http:
  routers:
    gnxcontainer-router:
      rule: Host(`webapp.teamgenetix.ch`) && PathPrefix(`/`)
      service: gnxcontainer-service
      entryPoints:
        - http
        - https
      tls:
        certResolver: myresolver

  services:
    gnxcontainer-service:
      loadBalancer:
        servers:
          - url: "http://gnxcontainer:8080"
